// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

export 'package:a9_ui/a9_ui.dart';
export 'package:uuid/uuid_value.dart';
export 'package:flutter_rust_bridge/src/actor_ref.dart';

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CounterResponse`, `CounterView`, `Dec`, `Inc`, `__GeneratedCounterMsg`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `hash_code`, `hash`, `initialize`, `process_msg`, `process`, `process`

/// Get a reference to the counter actor
/// This demonstrates our new ActorRef delegate integration
Future<ActorRef<Counter>> getCounter() =>
    RustLib.instance.api.crateApiSimpleGetCounter();

/// Increment the counter via ActorRef
Future<void> incrementCounter({
  required ActorRef<Counter> actorRef,
  required PlatformInt64 amount,
}) => RustLib.instance.api.crateApiSimpleIncrementCounter(
  actorRef: actorRef,
  amount: amount,
);

/// Decrement the counter via ActorRef
Future<void> decrementCounter({
  required ActorRef<Counter> actorRef,
  required PlatformInt64 amount,
}) => RustLib.instance.api.crateApiSimpleDecrementCounter(
  actorRef: actorRef,
  amount: amount,
);

class Counter {
  final PlatformInt64 value;

  const Counter({required this.value});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<Counter> newInstance() =>
      RustLib.instance.api.crateApiSimpleCounterNew();

  @override
  int get hashCode => value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Counter &&
          runtimeType == other.runtimeType &&
          value == other.value;
}
